### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by shafiquesalman96** [mgrewe/ovmf#1]
Trying 2nd installation and facing the error in line 26 of the openface_tracker i.e from openface import Openface  no module name open face found". Your guidance will be appreciated in this regard.
![a](https://user-images.githubusercontent.com/112179664/202439443-64b43011-3e7b-4224-adf0-a40a26d02fd4.jpg)

**Comment by mgrewe** [comment]
Hi @shafiquesalman96 ,

it seems that the openface python module was either not build correctly or cannot be found. Please check the following two points:

1. Did the compilation in step [2.4](https://github.com/mgrewe/ovmf/blob/main/INSTALLATION.md#24-configure-and-build-openface) finished successfully?
2. Is the path in the config file (see [step 2.6](https://github.com/mgrewe/ovmf/blob/main/INSTALLATION.md#26-configure-ovmf)) set correctly? The path specified for `openface_binary_dir` should contain the compiled python file.

Hope this helps. Cheers, Martin

**Comment by mgrewe** [comment]
Guess we can close this one!
