### ISSUE TITLE
Image sometimes being sent regardless of config?

### ISSUE THREAD

**Issue by rohitgupta3** [mgrewe/ovmf#2]
I don't know if I understand the entire repo too well but was wondering if, in the case of a module having both a sender and receiver(s), the module is sending the image regardless of the config. Specifically, should [this line](https://github.com/mgrewe/ovmf/blob/main/lib/module_base.py#L121) not follow the same logic as [this line](https://github.com/mgrewe/ovmf/blob/main/lib/module_base.py#L126)? Thanks.

EDIT: apologies, I realized that, despite how small the change would be, it might be more convenient to engage with a PR instead of commenting on an issue. So I created [this PR](https://github.com/mgrewe/ovmf/pull/3).

**Comment by mgrewe** [comment]
Thanks again @rohitgupta3 for the PR which has just been merged. Closing this.
